### ISSUE TITLE
Illuminate\Foundation\Auth\User in your BaseController instead of App\User

### ISSUE THREAD

**Issue by sergeByishimo** [spatie/laravel-welcome-notification#11]
Love the package! it's great!

I noticed that you are using laravel's `Illuminate\Foundation\Auth\User` in your `BaseController` instead of `App\User`, and in my case there is some custom configuration i've done to my model that are lost while authenticating the user. For example the `keyType` is set to string bcz i'm using uuid. 

I've had to copy and paste the controller for now, but hope you provide an answer for that soon to go back to using your controller.

**Comment by freekmurze** [comment]
Thank you for your kind words.

I currently don't have the time to improve on this.

If there is a straightforward, non-breaking way to allow your use case, feel free to send a PR! 👍
