### ISSUE TITLE
Can I use with Multiple Authentication[Users, Admins]?

### ISSUE THREAD

**Issue by petersowah** [spatie/laravel-welcome-notification#15]
I have two models; `User` and `Admin`. I'm trying to set the package up for admins to so they get an email to set a password for their account.

I created a WelcomeNewAdmins middleware. How do I get the Admin object in the WelcomesNewAdmins middleware?

**Comment by muarachmann** [comment]
Hey @petersowah did you find a way to get past this?

**Comment by petersowah** [comment]
Yeah, I was able to get past that.
