### ISSUE TITLE
Curious why `bcrypt` instead of `Hash::make`

### ISSUE THREAD

**Issue by andrewminion-luminfire** [spatie/laravel-welcome-notification#16]
I’m working on a new project using this package, and I’m extending the `WelcomeController` to include verifying a Google 2FA code in the `showWelcomeForm` controller.

I noticed you’re using `bcrypt` to hash passwords [on this line](https://github.com/spatie/laravel-welcome-notification/blob/8c28dbcba2928888d56dcc4be475c772f7bbf5ec/src/WelcomeController.php#L26) instead of the `Hash::make` facade and am curious:

1. Why you used that instead of the facade?
2. If I change my hash driver, will it break or require me to change to match my hash driver?

Thanks!

**Comment by freekmurze** [comment]
Under the hood `bcrypt` will use the same hasher as the one when you're using the `Hash` facade.

I think changing the driver will break it, yeah. I'm not 100% certain. Try it out to know for sure.

**Comment by andrewminion-luminfire** [comment]
Would there be any downside to using `Hash::make` instead of `bcrypt`?

**Comment by andrewminion-luminfire** [comment]
Tested using `argon` as the hash driver and it **did not** break. The passwords are stored a bit differently for each:

- bcrypt: `$2y$10$…`
- argon: `$argon2i$v=19$m=1024,t=2,p=2$…`
- argon2id: `$argon2id$v=19$m=1024,t=2,p=2$…`

I’m still wondering if the package should use `Hash::make` instead of `bcrypt` directly? If so, I’m happy to submit a PR, and if not, I’d love to learn why.

Thanks!

**Comment by freekmurze** [comment]
Unless there's an appealing reason to switch to the facade, I'm going to leave things as they are.
