### ISSUE TITLE
PHP 8.0 Compatibility

### ISSUE THREAD

**Issue by lloydowen** [spatie/laravel-welcome-notification#25]
With PHP 8.0 Released it would be great to update this to support that.

**Comment by CraigMonva** [comment]
@lloydowen #24 

I'm about to give this a shot.

**Comment by lloydowen** [comment]
> @lloydowen #24
> 
> I'm about to give this a shot.

I've just raised a PR for it also!

**Comment by CraigMonva** [comment]
Okay great, I'll hang back then :)

**Comment by freekmurze** [comment]
Merged PR, will be tagged in few minutes. Thanks all!
