### ISSUE TITLE
Attempt to read property "welcome_valid_until" on string

### ISSUE THREAD

**Issue by RoguePoma** [spatie/laravel-welcome-notification#38]
Hello, I've used this package with Laravel 8, and it worked a treat! Now I am working on a new project on Laravel 9 and whatever I do I can't get it to work.

Php Version: 8.1.6
Laravel Version: 9.19.0

This is the error message I receive: 
Attempt to read property "welcome_valid_until" on string

Looking deeper, it looks like the request in the WelcomesNewUsers doesn't pass a user object and just the id integer. But im unsure if I'm looking in the right place. 

Has anyone faced this issue? Or know a solution?

**Comment by dominikgeimer** [comment]
I am using it on Laravel 9 without any problem. Did you follow the instructions or did you modify anything specific? Maybe show some code.

**Comment by squpshift** [comment]
I'm also getting this error after trying to install this package for the first time today.

https://flareapp.io/share/xPQoY0k5#F47

**Comment by squpshift** [comment]
I resolved this by creating my own WelcomesNewUsers middleware
