### ISSUE TITLE
Security Flaw

### ISSUE THREAD

**Issue by nexgendevs** [spatie/laravel-welcome-notification#52]
Hi All,
I am using this package in one of my projects and found that it has a security flaw, I can see the URL sent via email has a signature in it. During my testing, I changed the value of that signature and could still set my initial password. Then I checked the code and realized the signature was not being checked/validated anywhere.

So, If I know that someone has been registered by an admin and we know the ID they got, we can set their initial password.

Below is the function responsible for setting the initial password. But it does not validate the signature value.

```
public function savePassword(Request $request, User $user)
    {
        $request->validate($this->rules());

        $user->password = Hash::make($request->password);
        $user->welcome_valid_until = null;
        $user->save();

        auth()->login($user);

        return $this->sendPasswordSavedResponse();
    }
```

**Comment by problem9** [comment]
It is validated in middleware WelcomesNewUsers::class. You have to add it to the routes.

[WelcomesNewUsers::class](https://github.com/spatie/laravel-welcome-notification?tab=readme-ov-file#registering-the-routes)
