### ISSUE TITLE
sendPasswordSavedResponse issue

### ISSUE THREAD

**Issue by liamseys** [spatie/laravel-welcome-notification#6]
Declaration of App\Http\Controllers\Auth\WelcomeController::sendPasswordSavedResponse() must be compatible with Spatie\WelcomeNotification\WelcomeController::sendPasswordSavedResponse(): Symfony\Component\HttpFoundation\Response

https://flareapp.io/share/17WEXJmX#F1

**Comment by freekmurze** [comment]
I've correct this in the docs. You'll need to add a `Symfony\Component\HttpFoundation\Response` return type hint.
