### ISSUE TITLE
Where are migrations?

### ISSUE THREAD

**Issue by goszowski** [spatie/laravel-welcome-notification#7]
package not contain migrations

**Comment by freekmurze** [comment]
The package contains a migration: https://github.com/spatie/laravel-welcome-notification/blob/master/database/migrations/add_welcome_valid_until_field_to_users_table.php.stub

**Comment by goszowski** [comment]
Directory database/migrations not exists.

ls vendor/spatie/laravel-welcome-notification
CHANGELOG.md  composer.json  CONTRIBUTING.md  LICENSE.md  README.md  resources  src
