### ISSUE TITLE
Directory database/migrations not exists.

### ISSUE THREAD

**Issue by goszowski** [spatie/laravel-welcome-notification#8]
Directory database/migrations not exists.

ls vendor/spatie/laravel-welcome-notification
CHANGELOG.md  composer.json  CONTRIBUTING.md  LICENSE.md  README.md  resources  src

_Originally posted by @goszowski in https://github.com/spatie/laravel-welcome-notification/issues/7#issuecomment-555057211_

**Comment by freekmurze** [comment]
It is not clear what you mean. Please provide more info or steps to recreate the problem you are facing.

**Comment by xseguib** [comment]
Migrations works fine
